server:
  port: 8082

spring:
  config:
    import:
      - optional:nacos:common-config.yaml
      - optional:nacos:system-service.yaml
      - optional:nacos:mysql-service.yaml
      - optional:nacos:redis-service.yaml

# 日志配置
logging:
  level:
    com.trae.micro: debug